### ISSUE TITLE
Endless Loop at Jump Step

### ISSUE THREAD

**Issue by Witchblade101** [radicamc/supreme-spoon#16]
Michael,

I tried running Stage 1 as a test this afternoon. Everything looked OK until it tried the jump detection step, then it seemed to get into an endless loop. After an hour of no progress I killed the run.

My Run_DMS.yaml and the console output are attached.

[run_DMS.yaml.txt](https://github.com/radicamc/supreme-spoon/files/11739686/run_DMS.yaml.txt)

[output.txt](https://github.com/radicamc/supreme-spoon/files/11739687/output.txt)

**Comment by radicamc** [comment]
Hey Doug, 
Hm this is interesting. Is all that output from a single run, or were multiple runs attempted, then killed, the reattempted? It looks like the code reached the jump detection step, and then somehow reverted back to the beginning?

**Comment by Witchblade101** [comment]
A single run. It looks like it went fine until it got to the Jump step, then started the endless repeating until I eventually killed it.

**Comment by radicamc** [comment]
As discussed, it seems like this may be a problem with how your OS is interacting with the jwst JumpStep multithreading.

**Comment by radicamc** [comment]
From discussions it seems like everything is working now, so I'm going to go ahead and close this issue.
