### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by njcuk9999** [radicamc/supreme-spoon#17]
I think you should probably add that one should really cite the JWST pipeline in your citation sections, supreme-spoon relies heavily on stage 1 and stage 2 pipeline steps. 

i.e. at the least this needs to change to include the jwst pipeline
> Lastly, you should cite the libraries upon which this code is built, namely: [numpy](https://ui.adsabs.harvard.edu/abs/2020Natur.585..357H/abstract), [scipy](https://ui.adsabs.harvard.edu/abs/2020NatMe..17..261V/abstract), and [astropy](https://ui.adsabs.harvard.edu/abs/2013A%26A...558A..33A/abstract).

**Comment by njcuk9999** [comment]
There is indeed one in the standard citation.cff on the jwst pipeline github:
https://github.com/spacetelescope/jwst/blob/master/CITATION.cff

Basically links to here:
https://zenodo.org/record/7038885/export/hx

**Comment by radicamc** [comment]
Fixed in [39d43bb](https://github.com/radicamc/supreme-spoon/commit/39d43bb891c2165a1aa73a0fcb7076446aacddab)
