### ISSUE TITLE
error: wavebin index out of range. Comes from stage4.read_ld_coefs

### ISSUE THREAD

**Issue by kmorel2892** [radicamc/supreme-spoon#26]
https://github.com/radicamc/supreme-spoon/blob/07db39a7aa20590b1ff68ecdcdbadcc5bb1013c2/supreme_spoon/fit_lightcurves.py#L219

**Comment by radicamc** [comment]
I have not been able to reproduce this. Do you have an error readout so I can see more specifically where this is stemming from?
