### ISSUE TITLE
Calculates stability pca even if False

### ISSUE THREAD

**Issue by kmorel2892** [radicamc/supreme-spoon#27]
https://github.com/radicamc/supreme-spoon/blob/d0da60d9d5979e47eaabccecaa958392abf707b3/supreme_spoon/stage2.py#L985

**Comment by radicamc** [comment]
Fixed in [916abeb](https://github.com/radicamc/supreme-spoon/commit/916abebf79e089c5efdaf530041cd0e00226e48d). Though why would one ever _not_ want to run the PCA, its magic!
